/* Automagically generated, do not edit! */
static const u_char t01_head1[] = ""
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width\">"
"<style type=\"text/css\">"
"html,"
"body {"
"background: #fff;"
"font-family: \"Microsoft YaHei\", \"PingFang SC\", \"WenQuanYi Micro Hei\", sans-serif;"
"}"
"\n"
"body {"
"margin: auto;"
"max-width: 1000px;"
"padding: 15px;"
"color: #333;"
"}"
"\n"
"h1 {"
"color: #2b2b2b;"
"font-size: 1.8em;"
"text-align: left;"
"padding-bottom: 15px;"
"word-wrap: break-word;"
"}"
"\n"
"a,"
"a:hover,"
"a:active,"
"a:visited {"
"text-decoration: none;"
"}"
"\n"
"table a,"
"table a:visited {"
"color: #404040;"
"}"
"\n"
"table a:hover,"
"table a:active {"
"color: #101010;"
"}"
"\n"
"#list {"
"width: 100%;"
"border: none;"
"margin-bottom: 60px;"
"}"
"\n"
"table {"
"overflow-x: auto;"
"border-collapse: collapse;"
"}"
"\n"
"table th,"
"table td {"
"padding: 8px;"
"}"
"\n"
"table thead {"
"text-align: left;"
"background: #eee;"
"}"
"\n"
"table th {"
"text-align: left;"
"font-weight: bold;"
"}"
"\n"
"table td {"
"word-break: break-all;"
"border-bottom: 1px solid #edf1f5;"
"}"
"\n"
"table th:last-child,"
"table td:last-child {"
"text-align: right;"
"}"
"\n"
"table tr:hover {"
"background: #f1f2f3;"
"}"
"\n"
"table tbody tr a:before {"
"content: '';"
"padding-right: 8px;"
"}"
"\n"
"table tbody tr a:before {"
"content: \"📄\";"
"}"
"\n"
"table tbody tr a[href$=\"/\"]:before {"
"content: '📁';"
"}"
"\n"
"table tbody tr a[href$=\".mp3\"]:before,"
"table tbody tr a[href$=\".aac\"]:before,"
"table tbody tr a[href$=\".wav\"]:before,"
"table tbody tr a[href$=\".flac\"]:before {"
"content: '🎵';"
"}"
"\n"
"table tbody tr a[href$=\".mp4\"]:before,"
"table tbody tr a[href$=\".flv\"]:before,"
"table tbody tr a[href$=\".avi\"]:before,"
"table tbody tr a[href$=\".mkv\"]:before,"
"table tbody tr a[href$=\".mov\"]:before,"
"table tbody tr a[href$=\".webm\"]:before {"
"content: '🎞️';"
"}"
"\n"
"table tbody tr a[href$=\".bmp\"]:before,"
"table tbody tr a[href$=\".png\"]:before,"
"table tbody tr a[href$=\".gif\"]:before,"
"table tbody tr a[href$=\".jpg\"]:before,"
"table tbody tr a[href$=\".jpeg\"]:before,"
"table tbody tr a[href$=\".webp\"]:before {"
"content: '🖼️';"
"}"
"\n"
"table tbody tr a[href$=\".rar\"]:before,"
"table tbody tr a[href$=\".zip\"]:before,"
"table tbody tr a[href$=\".7z\"]:before,"
"table tbody tr a[href$=\".gz\"]:before,"
"table tbody tr a[href$=\".tar\"]:before {"
"content: '📦️';"
"}"
"\n"
"table tbody tr a[href$=\".exe\"]:before,"
"table tbody tr a[href$=\".dll\"]:before,"
"table tbody tr a[href$=\".apk\"]:before,"
"table tbody tr a[href$=\".jar\"]:before,"
"table tbody tr a[href$=\".app\"]:before,"
"table tbody tr a[href$=\".run\"]:before,"
"table tbody tr a[href$=\".ipa\"]:before,"
"table tbody tr a[href$=\".dmg\"]:before {"
"content: '💿';"
"}"
"</style>"
"\n"
;
static const u_char t02_head2[] = ""
"\n"
"<title>浏览文件</title>"
"<title>索引 "
;
static const u_char t03_head3[] = ""
"</title>"
"\n"
"</head>"
;
static const u_char t04_body1[] = ""
"<body>"
"<h1>索引 "
;
static const u_char t05_body2[] = ""
"</h1>"
"\n"
;
static const u_char t06_list1[] = ""
"<table id=\"list\">"
"<thead>"
"<tr>"
"<th colspan=\"5\"><a href=\"?C=N&amp;O=A\">文件名</a>&nbsp;<a href=\"?C=N&amp;O=D\">&nbsp;&darr;&nbsp;</a></th>"
"<th colspan=\"1\"><a href=\"?C=S&amp;O=A\">大小</a>&nbsp;<a href=\"?C=S&amp;O=D\">&nbsp;&darr;&nbsp;</a></th>"
"<th colspan=\"2\"><a href=\"?C=M&amp;O=A\">日期</a>&nbsp;<a href=\"?C=M&amp;O=D\">&nbsp;&darr;&nbsp;</a></th>"
"</tr>"
"</thead>"
"\n"
"<tbody>"
;
static const u_char t_parentdir_entry[] = ""
"<tr>"
"<td colspan=\"5\" class=\"link\"><a href=\"../?C=N&amp;O=A\">上级目录/</a></td>"
"<td colspan=\"1\" class=\"size\">-</td>"
"<td colspan=\"2\" class=\"date\">-</td>"
"</tr>"
"\n"
;
static const u_char t07_list2[] = ""
"</tbody>"
"</table>"
;
static const u_char t08_foot1[] = ""
"</body>"
"</html>"
;
#define NFI_TEMPLATE_SIZE (0 \
	+ nfi_sizeof_ssz(t01_head1) \
	+ nfi_sizeof_ssz(t02_head2) \
	+ nfi_sizeof_ssz(t03_head3) \
	+ nfi_sizeof_ssz(t04_body1) \
	+ nfi_sizeof_ssz(t05_body2) \
	+ nfi_sizeof_ssz(t06_list1) \
	+ nfi_sizeof_ssz(t_parentdir_entry) \
	+ nfi_sizeof_ssz(t07_list2) \
	+ nfi_sizeof_ssz(t08_foot1) \
	)
